server:
  port: 9527

spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      routes:
        - id: payment_routh  #路由的ID，没有固定规则但是唯一，建议配合服务名
#          uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**    #断言，路径相匹配的进行路由
            - After=2020-04-06T15:05:24.599+08:00[Asia/Shanghai]
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务名进行路由

#        - id: payment_routh2  #路由的ID，没有固定规则但是唯一，建议配合服务名
#            uri: http://localhost:8001  #匹配后提供服务的路由地址
#            predicates:
#              - Path=/payment/lb/**    #断言，路径相匹配的进行路由
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway9527
    prefer-ip-address: true
logging:
  level:
    org.springframework.cloud.gateway: debug