server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: order80
    prefer-ip-address: true
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 10000
#        readTimeout: 60000

#设置feign客户端超时时间（openfeign默认支持ribbon），默认1s
#原因：被调用方处理业务需要一定时间
ribbon:
  #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #建立连接后从服务器读取到可用资源的时间
  ConnectTimeout: 5000

logging:
  level:
    #feign日志 以什么级别监控哪个接口
    com.zeny.springcloud.service.PaymentFeignService: debug
