server:
  port: 80

spring:
  application:
    name: consul-consumer-order
#consul注册中心
  cloud:
    consul:
      host: 192.168.1.19
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true

